[issue-103] The percentage difference is rounded and passes the tests
wswebcreation/webdriver-image-comparison pull request #105
Opened 2022-05-14 19:43 UTC by jesusfj710

https://github.com/wswebcreation/webdriver-image-comparison/issues/103

2022-05-22 06:29 UTC, wswebcreation requested changes
Hi @jesusfj710

Thanks for this PR, I see it's in draft, but already added some minor comments. Are there any doubts/concerns that you have regarding this PR?

2022-05-22 06:29 UTC, wswebcreation commented on lib/methods/images.ts
>      ? data.rawMisMatchPercentage
```suggestion
    ? rawMisMatchPercentage
```

2022-05-22 06:29 UTC, wswebcreation commented on lib/methods/images.ts
> +  const misMatchPercentage = data.rawMisMatchPercentage;
When we're touching this code, can we make it more clear by changing the name of the const? We then also need to change it on multiple places, including line 254/255

```suggestion
  const rawMisMatchPercentage = data.rawMisMatchPercentage;
```

2022-05-22 06:29 UTC, wswebcreation commented on lib/methods/images.ts
>      : Number(data.rawMisMatchPercentage.toFixed(2));
```suggestion
    : Number(rawMisMatchPercentage.toFixed(2));
```

2022-08-09 09:01 UTC, jesus-e2y commented
I'm sorry I haven't had time to check it, but I need to find the right time. I will probably go over and do another draft that is more complete and then we can discuss it.

2022-08-09 09:05 UTC, jesusfj710 commented
I'm sorry I haven't had time to check it, but I need to find the right time. I will probably go over and do another draft that is more complete and then we can discuss it.

2022-08-27 16:05 UTC, jesusfj710 commented
@wswebcreation maybe now? 🤔

2022-09-10 06:10 UTC, wswebcreation commented
Thanks @jesusfj710 

I'll check this one later. This might be a breaking change and will need to update at least the https://github.com/wswebcreation/wdio-image-comparison-service module.

Will put this on my TODO list.

2022-09-18 07:24 UTC, wswebcreation commented
Thanks for you work. 
This will be a breaking change because it will now by default return `0.00` instead of `0`. I'm going to release this in a few days because I want to fix some more things

2022-09-18 07:24 UTC, wswebcreation approved these changes

2022-10-10 14:23 UTC, merged

2022-10-16 07:18 UTC, wswebcreation commented
@jesusfj710 

I've been thinking about this and I had a lot of breaking tests, so I reverted your PR and updated it to the following https://github.com/wswebcreation/webdriver-image-comparison/releases/tag/v1.0.2. I hope you don't mind

2022-10-17 14:10 UTC, jesusfj710 commented
Ok, but at some point this should be handled better or at least made clear in the `readme.MD` or in the wiki how this can affect the use of the library.